### ISSUE TITLE
[Docs] README.md 수정

### ISSUE THREAD

**Issue by hossi97** [Team-RecruTe/RecruTe-Service#6]
## Description
README 내용을 수정합니다.

## To-Do
- [x] 기술스택 위치 이동
- [x] 진행 방법 소제목 추가
- [x] 코드 리뷰 방식 수정
