### ISSUE TITLE
[Chore] 서비스 코드 구조 설계 및 구현

### ISSUE THREAD

**Issue by hossi97** [Team-RecruTe/RecruTe-Service#87]
## Description
서비스별로 부여한 코드를 구조화합니다.

## To-Do
- [x] 서비스 코드 구조 설계
- [x] 서비스 코드 구조 구현
- [x] 서비스 코드 구현 테스트
